spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/starter
    username: starter
    password: starter
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    properties:
      hibernate:
        # 로컬에서만 실행 쿼리 로깅
        show_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
